"""
data_loader.py — Load, clean, and preprocess the SHL product catalog.

Preprocessing pipeline:
  1. Load JSON; filter to status == 'ok'
  2. Parse duration → integer minutes
  3. Build rich 'document' string for embedding
  4. Return list[dict] with all original fields + 'document' + 'duration_minutes'
"""
import json
import re
from pathlib import Path
from typing import Optional

from src.config import RAW_CATALOG_PATH, CLEANED_CATALOG_PATH


def _is_individual_test_solution(item: dict) -> bool:
    """
    Keep only in-scope catalog entries.

    The assignment excludes packaged Job Solutions. The scraped JSON does not
    expose a dedicated product-type field, so we filter out those packages by
    name and URL while keeping individual tests, simulations, and reports.
    """
    if item.get("status") != "ok":
        return False

    name = item.get("name", "").strip().lower()
    link = item.get("link", "").strip().lower()

    if re.search(r"\bsolution\b", name):
        return False
    if re.search(r"(?:^|[-/])solution(?:[-/]|$)", link):
        return False

    return True


# ── Duration parsing ──────────────────────────────────────────────────────────

def _parse_duration(duration: str, duration_raw: str) -> Optional[int]:
    """Extract integer minutes from the duration fields. Returns None if unknown."""
    for text in (duration, duration_raw):
        if not text:
            continue
        match = re.search(r"(\d+)", text)
        if match:
            return int(match.group(1))
    return None


# ── Document builder ──────────────────────────────────────────────────────────

def _build_document(item: dict) -> str:
    """
    Concatenate all meaningful fields into one rich string for embedding.
    Full context is crucial: a query for 'data analysis' must match
    'Numerical Reasoning' via the description text.
    """
    name = item.get("name", "")
    description = item.get("description", "")
    keys = ", ".join(item.get("keys", [])) or "N/A"
    job_levels = ", ".join(item.get("job_levels", [])) or "N/A"
    duration = item.get("duration", "") or "Unknown"
    remote = item.get("remote", "no")
    adaptive = item.get("adaptive", "no")

    return (
        f"Assessment: {name}. "
        f"Description: {description}. "
        f"Test Types: {keys}. "
        f"Job Levels: {job_levels}. "
        f"Duration: {duration}. "
        f"Remote: {remote}. "
        f"Adaptive: {adaptive}."
    )


# ── Public API ────────────────────────────────────────────────────────────────

def load_raw_catalog(path: Path = RAW_CATALOG_PATH) -> list[dict]:
    """Load the raw catalog and keep only in-scope individual solutions."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return [item for item in data if _is_individual_test_solution(item)]


def preprocess_catalog(raw: list[dict]) -> list[dict]:
    """
    Clean and enrich each assessment record.
    Adds 'duration_minutes' (int | None) and 'document' (str) fields.
    """
    processed = []
    for item in raw:
        cleaned = dict(item)
        cleaned["duration_minutes"] = _parse_duration(
            item.get("duration", ""), item.get("duration_raw", "")
        )
        cleaned["document"] = _build_document(item)
        processed.append(cleaned)
    return processed


def load_cleaned_catalog(path: Path = CLEANED_CATALOG_PATH) -> list[dict]:
    """Load the pre-processed catalog from disk (generated by scripts/preprocess.py)."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_cleaned_catalog(data: list[dict], path: Path = CLEANED_CATALOG_PATH) -> None:
    """Persist the cleaned catalog to disk."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"[data_loader] Saved {len(data)} assessments → {path}")
